from .events import FillEvent

class ExecutionHandler:
    """
    The ExecutionHandler abstract class handles the interaction
    between a set of order objects generated by a Portfolio and
    the ultimate set of Fill objects that actually occur in the
    market.
    """
    def execute_order(self, event):
        raise NotImplementedError("Should implement execute_order()")

class SimulatedExecutionHandler(ExecutionHandler):
    """
    The simulated execution handler simply converts all order
    objects into their equivalent fill objects automatically
    without latency, slippage or fill-ratio issues.

    This allows a straightforward "first pass" test of any strategy.
    """
    def __init__(self, events, bars):
        self.events = events
        self.bars = bars

    def execute_order(self, event):
        """
        Simply converts Order objects into Fill objects naively,
        i.e. without any latency, slippage or fill ratio problems.
        Uses the next open price for realism if possible, or close if not.
        """
        if event.type == 'ORDER':
            # For simplicity in MVP, we use the last available close price as the fill cost.
            # In a true system, we'd use the NEXT open price to avoid look-ahead bias.
            try:
                fill_cost = self.bars.get_latest_bar_value(event.symbol, "close")
                timeindex = self.bars.get_latest_bar_datetime(event.symbol)
            except Exception:
                fill_cost = 0.0
                timeindex = None

            fill_event = FillEvent(
                timeindex, event.symbol, 'NSE', event.quantity,
                event.direction, fill_cost
            )
            self.events.put(fill_event)
